language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
install:
  - npm install
before_script:
  - npm install npm
script:
  - npm test
sudo: false
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
